# Discrete Markov Chains and Stationary Distributions

This is BONUS content related to Day 17, where we introduce Markov models for discrete random variables.


## Random variables

* $z_1, z_2, \ldots z_T$, where $t \in \{1, 2, \ldots T$ indexes the discrete timestep
* Each is a discrete random variable: $z_t \in \{1, 2, \ldots K\}$

## Parameters

* $\pi$ is the $K$-length initial probability vector. $\pi \in \Delta^K$ (non-negative, sums to one)
* $A$ is a $K \times K$ transition matrix. For each row $j$, we have $A_j \in \Delta^K$ (all entries are non-negative and each *row* sums to one).

## Probability mass function

* $p(z_1) = \text{CatPMF}(z_1 | \pi_1, \pi_2, \ldots \pi_K)$, which implies $p(z_1 = k) = \pi_k$
* $p(z_t | z_{t-1}=j) = \text{CatPMF}(z_t | A_{j1}, A_{j2}, \ldots A_{jK})$, which implies $p(z_t = k | z_{t-1}=j) = A_{jk}$

## Key takeaways

* New concept: 'Stationary distribution' or 'Equilibrium distribution', the limiting distribution of $p(z_t)$ as $t \rightarrow \infty$

* When does the stationary distribution exist? As long it is "ergodic", which (intuitively) means each state has *some* probability of reaching every other state. 

* Below, we'll see 3 ways to compute a stationary distribution:
* * Manually compute the marginal $p(z_t)$ at each timestep $t \in 1, 2, \ldots T$. Observe it become stationary
* * Look at limits of multiplying the transition matrix: $A \cdot A \cdot A \cdot \ldots$. Eventually, will converge to a matrix where rows are the stationary distribution.
* * Look at eigenvectors of $A^T$. Find the eigenvector corresponding to eigenvalue 1 and renormalize it so it sums to one.


## Things to remember

In the code below, we need to use zero-based indexing (like python always does). 

So, the "first" timestep is t=0.


In [42]:
import numpy as np

In [4]:
## Number of states
K = 2

In [18]:
## Transition probabilities
A_KK = np.asarray([[0.9, 0.1], [0.2, 0.8]])

In [19]:
print(A_KK)

[[0.9 0.1]
 [0.2 0.8]]


# What happens to p(z[t]) after many timesteps? Converge to one distribution

In [22]:
pi_K = np.asarray([0.5, 0.5])
for t in range(100):
    if t == 0:
        proba_K = 1.0 * pi_K
    elif t > 0:
        proba_K = np.dot(proba_K, A_KK)        
    print("after t=%3d steps: p(z[t]) = Cat(%.4f, %.4f)" % (t, proba_K[0], proba_K[1]))

after t=  0 steps: p(z[t]) = Cat(0.5000, 0.5000)
after t=  1 steps: p(z[t]) = Cat(0.5500, 0.4500)
after t=  2 steps: p(z[t]) = Cat(0.5850, 0.4150)
after t=  3 steps: p(z[t]) = Cat(0.6095, 0.3905)
after t=  4 steps: p(z[t]) = Cat(0.6267, 0.3734)
after t=  5 steps: p(z[t]) = Cat(0.6387, 0.3613)
after t=  6 steps: p(z[t]) = Cat(0.6471, 0.3529)
after t=  7 steps: p(z[t]) = Cat(0.6529, 0.3471)
after t=  8 steps: p(z[t]) = Cat(0.6571, 0.3429)
after t=  9 steps: p(z[t]) = Cat(0.6599, 0.3401)
after t= 10 steps: p(z[t]) = Cat(0.6620, 0.3380)
after t= 11 steps: p(z[t]) = Cat(0.6634, 0.3366)
after t= 12 steps: p(z[t]) = Cat(0.6644, 0.3356)
after t= 13 steps: p(z[t]) = Cat(0.6651, 0.3349)
after t= 14 steps: p(z[t]) = Cat(0.6655, 0.3345)
after t= 15 steps: p(z[t]) = Cat(0.6659, 0.3341)
after t= 16 steps: p(z[t]) = Cat(0.6661, 0.3339)
after t= 17 steps: p(z[t]) = Cat(0.6663, 0.3337)
after t= 18 steps: p(z[t]) = Cat(0.6664, 0.3336)
after t= 19 steps: p(z[t]) = Cat(0.6665, 0.3335)
after t= 20 steps: p

# What about starting from pi_K = [0.01, 0.99]? Converge to same distribution

In [23]:
pi_K = np.asarray([0.01, 0.99])
for t in range(100):
    if t == 0:
        proba_K = 1.0 * pi_K
    elif t > 0:
        proba_K = np.dot(proba_K, A_KK)
    print("after t=%3d steps: p(z[t]) = Cat(%.4f, %.4f)" % (t, proba_K[0], proba_K[1]))

after t=  0 steps: p(z[t]) = Cat(0.0100, 0.9900)
after t=  1 steps: p(z[t]) = Cat(0.2070, 0.7930)
after t=  2 steps: p(z[t]) = Cat(0.3449, 0.6551)
after t=  3 steps: p(z[t]) = Cat(0.4414, 0.5586)
after t=  4 steps: p(z[t]) = Cat(0.5090, 0.4910)
after t=  5 steps: p(z[t]) = Cat(0.5563, 0.4437)
after t=  6 steps: p(z[t]) = Cat(0.5894, 0.4106)
after t=  7 steps: p(z[t]) = Cat(0.6126, 0.3874)
after t=  8 steps: p(z[t]) = Cat(0.6288, 0.3712)
after t=  9 steps: p(z[t]) = Cat(0.6402, 0.3598)
after t= 10 steps: p(z[t]) = Cat(0.6481, 0.3519)
after t= 11 steps: p(z[t]) = Cat(0.6537, 0.3463)
after t= 12 steps: p(z[t]) = Cat(0.6576, 0.3424)
after t= 13 steps: p(z[t]) = Cat(0.6603, 0.3397)
after t= 14 steps: p(z[t]) = Cat(0.6622, 0.3378)
after t= 15 steps: p(z[t]) = Cat(0.6635, 0.3365)
after t= 16 steps: p(z[t]) = Cat(0.6645, 0.3355)
after t= 17 steps: p(z[t]) = Cat(0.6651, 0.3349)
after t= 18 steps: p(z[t]) = Cat(0.6656, 0.3344)
after t= 19 steps: p(z[t]) = Cat(0.6659, 0.3341)
after t= 20 steps: p

# What about starting from pi_K = [0.99, 0.01]? Converge to same distribution

In [25]:
pi_K = np.asarray([0.99, 0.01])
for t in range(100):
    if t == 0:
        proba_K = 1.0 * pi_K
    elif t > 0:
        proba_K = np.dot(proba_K, A_KK)
    print("after t=%3d steps: p(z[t]) = Cat(%.4f, %.4f)" % (t, proba_K[0], proba_K[1]))

after t=  0 steps: p(z[t]) = Cat(0.9900, 0.0100)
after t=  1 steps: p(z[t]) = Cat(0.8930, 0.1070)
after t=  2 steps: p(z[t]) = Cat(0.8251, 0.1749)
after t=  3 steps: p(z[t]) = Cat(0.7776, 0.2224)
after t=  4 steps: p(z[t]) = Cat(0.7443, 0.2557)
after t=  5 steps: p(z[t]) = Cat(0.7210, 0.2790)
after t=  6 steps: p(z[t]) = Cat(0.7047, 0.2953)
after t=  7 steps: p(z[t]) = Cat(0.6933, 0.3067)
after t=  8 steps: p(z[t]) = Cat(0.6853, 0.3147)
after t=  9 steps: p(z[t]) = Cat(0.6797, 0.3203)
after t= 10 steps: p(z[t]) = Cat(0.6758, 0.3242)
after t= 11 steps: p(z[t]) = Cat(0.6731, 0.3269)
after t= 12 steps: p(z[t]) = Cat(0.6711, 0.3289)
after t= 13 steps: p(z[t]) = Cat(0.6698, 0.3302)
after t= 14 steps: p(z[t]) = Cat(0.6689, 0.3311)
after t= 15 steps: p(z[t]) = Cat(0.6682, 0.3318)
after t= 16 steps: p(z[t]) = Cat(0.6677, 0.3323)
after t= 17 steps: p(z[t]) = Cat(0.6674, 0.3326)
after t= 18 steps: p(z[t]) = Cat(0.6672, 0.3328)
after t= 19 steps: p(z[t]) = Cat(0.6670, 0.3330)
after t= 20 steps: p

# What is the limit of many products of the transition matrix?



In [40]:
np.set_printoptions(precision=2)
val_KK = A_KK
for t in range(100):
    val_KK = np.dot(val_KK, A_KK)
    msg = "--- after %3d steps: A_KK=\n%s" % (t, str(val_KK))
    print(msg)

--- after   0 steps: A_KK=
[[0.83 0.17]
 [0.34 0.66]]
--- after   1 steps: A_KK=
[[0.78 0.22]
 [0.44 0.56]]
--- after   2 steps: A_KK=
[[0.75 0.25]
 [0.51 0.49]]
--- after   3 steps: A_KK=
[[0.72 0.28]
 [0.55 0.45]]
--- after   4 steps: A_KK=
[[0.71 0.29]
 [0.59 0.41]]
--- after   5 steps: A_KK=
[[0.69 0.31]
 [0.61 0.39]]
--- after   6 steps: A_KK=
[[0.69 0.31]
 [0.63 0.37]]
--- after   7 steps: A_KK=
[[0.68 0.32]
 [0.64 0.36]]
--- after   8 steps: A_KK=
[[0.68 0.32]
 [0.65 0.35]]
--- after   9 steps: A_KK=
[[0.67 0.33]
 [0.65 0.35]]
--- after  10 steps: A_KK=
[[0.67 0.33]
 [0.66 0.34]]
--- after  11 steps: A_KK=
[[0.67 0.33]
 [0.66 0.34]]
--- after  12 steps: A_KK=
[[0.67 0.33]
 [0.66 0.34]]
--- after  13 steps: A_KK=
[[0.67 0.33]
 [0.66 0.34]]
--- after  14 steps: A_KK=
[[0.67 0.33]
 [0.66 0.34]]
--- after  15 steps: A_KK=
[[0.67 0.33]
 [0.67 0.33]]
--- after  16 steps: A_KK=
[[0.67 0.33]
 [0.67 0.33]]
--- after  17 steps: A_KK=
[[0.67 0.33]
 [0.67 0.33]]
--- after  18 steps: A_KK=
[

In [32]:
lam_K, V_KK = np.linalg.eig(A_KK.T)

In [33]:
lam_K

array([1. , 0.7])

In [34]:
V_KK

array([[ 0.89, -0.71],
       [ 0.45,  0.71]])

In [36]:
V_KK[:,0] / np.sum(V_KK[:,0])

array([0.67, 0.33])